<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container77BAOq0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container77BAOq0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container77BAOq0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container77BAOq0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container77BAOq0\App_KernelDevDebugContainer([
    'container.build_hash' => '77BAOq0',
    'container.build_id' => '0fb038f8',
    'container.build_time' => 1735676753,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container77BAOq0');
