<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPB9wUxN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPB9wUxN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPB9wUxN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPB9wUxN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPB9wUxN\App_KernelDevDebugContainer([
    'container.build_hash' => 'PB9wUxN',
    'container.build_id' => '6f186c70',
    'container.build_time' => 1733495984,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPB9wUxN');
