nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
